import os
import ast
import re
import math
import copy
import logging
from pathlib import Path
from typing import Dict, List, Any, Set, Tuple

def percentile(data: List[float], p: float) -> float:
    if not data:
        return 0.0
    data = sorted(data)
    n = len(data)
    k = (n - 1) * (p / 100.0)
    f = math.floor(k)
    c = math.ceil(k)
    if f == c:
        return data[int(k)]
    d0 = data[int(f)] * (c - k)
    d1 = data[int(c)] * (k - f)
    return d0 + d1

def compute_stats(data: List[float]) -> Dict[str, float]:
    if not data:
        return {"min": 0, "max": 0, "mean": 0, "median": 0, "p75": 0, "p90": 0, "total": 0}
    data = sorted(data)
    n = len(data)
    total = sum(data)
    return {
        "min": data[0],
        "max": data[-1],
        "mean": total / n if n > 0 else 0,
        "median": percentile(data, 50),
        "p75": percentile(data, 75),
        "p90": percentile(data, 90),
        "total": total
    }

EXCLUDE_DIRS = {
    'node_modules', '.git', '.vscode', '.idea', '__pycache__', 
    'venv', 'env', '.env', 'dist', 'build', 'out', 'target', 'vendor',
    'coverage', '.next', '.nuxt', 'tmp', 'temp'
}
CODE_EXTENSIONS = {
    '.py': 'python', '.js': 'javascript', '.jsx': 'javascript',
    '.ts': 'typescript', '.tsx': 'typescript', '.java': 'java',
    '.c': 'c', '.cpp': 'cpp', '.cs': 'csharp', '.go': 'go',
    '.rs': 'rust', '.rb': 'ruby', '.php': 'php', '.swift': 'swift',
    '.kt': 'kotlin', '.scala': 'scala', '.html': 'html', '.css': 'css',
    '.sql': 'sql', '.sh': 'shell', '.json': 'json', '.yaml': 'yaml', '.md': 'markdown'
}

# Safety caps to prevent hangs on large/adversarial repos
MAX_FILE_BYTES = 512_000   # Skip files larger than 512 KB
MAX_FILES_PER_REPO = 200   # Stop walking after 200 usable files per session

RE_SNAKE = re.compile(r'^[a-z_][a-z0-9_]*$')
RE_CAMEL = re.compile(r'^[a-z][a-zA-Z0-9]*$')
RE_PASCAL = re.compile(r'^[A-Z][a-zA-Z0-9]*$')
RE_UPPER = re.compile(r'^[A-Z_][A-Z0-9_]*$')
RE_TODO = re.compile(r'(?i)\b(todo|fixme|hack|bug)\b')
RE_BARE_EXCEPT = re.compile(r'except\s*:|except\s+Exception\s*:')
RE_EVAL = re.compile(r'\b(eval|exec|Function|innerHTML)\s*(\(|=)')
RE_SECRET = re.compile(r'(?i)(password|secret|api_key|token|bearer)["\']?\s*[:=]\s*["\'][a-zA-Z0-9_.-]{8,}["\']')
RE_AI_PATTERN = re.compile(r'(?i)(as an ai|language model|chatgpt|openai|generated by ai)')

def classify_name(name: str) -> str:
    if RE_UPPER.match(name): return 'UPPER_CASE'
    if RE_PASCAL.match(name): return 'PascalCase'
    if RE_CAMEL.match(name): return 'camelCase'
    if RE_SNAKE.match(name): return 'snake_case'
    return 'other'

def is_usable_file(filepath: str) -> bool:
    parts = Path(filepath).parts
    if any(p in EXCLUDE_DIRS for p in parts):
        return False
    ext = os.path.splitext(filepath)[1].lower()
    return ext in CODE_EXTENSIONS or os.path.basename(filepath) in ['requirements.txt', 'package.json']

class PythonVisitor(ast.NodeVisitor):
    def __init__(self):
        self.functions = []
        self.function_details = []
        self.classes = []
        self.imports = []
        self.complexity_scores = []
        self.function_lengths = []
        self.names = []
        self.identifier_lengths = []
        
        self.current_depth = 0
        self.nesting_depths = []
        self.control_flow = {'if': 0, 'for': 0, 'while': 0, 'try': 0, 'break': 0, 'continue': 0, 'yield': 0, 'await': 0}
        self.ast_structures = {'list_comp': 0, 'dict_comp': 0, 'lambda': 0, 'decorators': 0, 'type_hints': 0}
        self.error_handling = {'raise': 0, 'custom_exceptions': 0}
        self.oop = {'inheritance_count': 0, 'super_calls': 0, 'static_methods': 0, 'class_methods': 0}
        self.import_habits = {'aliased': 0, 'from_import': 0, 'relative': 0}
        self.idioms = {'is_none': 0, 'name_main': 0}

    def generic_visit(self, node):
        is_block = hasattr(node, 'body') and isinstance(node.body, list)
        if is_block: self.current_depth += 1
        super().generic_visit(node)
        if is_block:
            self.nesting_depths.append(self.current_depth)
            self.current_depth -= 1

    def register_name(self, name: str, ntype: str):
        self.names.append((name, ntype))
        self.identifier_lengths.append(len(name))

    def visit_FunctionDef(self, node):
        self.functions.append(node.name)
        self.register_name(node.name, 'function')
        flen = getattr(node, 'end_lineno', node.lineno) - node.lineno + 1
        self.function_lengths.append(flen)
        
        if node.decorator_list:
            self.ast_structures['decorators'] += len(node.decorator_list)
            for dec in node.decorator_list:
                if isinstance(dec, ast.Name):
                    if dec.id == 'staticmethod': self.oop['static_methods'] += 1
                    elif dec.id == 'classmethod': self.oop['class_methods'] += 1
                    
        if node.returns or any(arg.annotation for arg in node.args.args):
            self.ast_structures['type_hints'] += 1
            
        complexity = 1
        for child in ast.walk(node):
            if isinstance(child, (ast.If, ast.For, ast.While, ast.Try, ast.With, ast.ExceptHandler, ast.BoolOp)):
                if isinstance(child, ast.BoolOp):
                    complexity += len(child.values) - 1
                else:
                    complexity += 1
        self.complexity_scores.append(complexity)
        
        self.function_details.append({
            "name": node.name,
            "line": node.lineno,
            "length": flen,
            "complexity": complexity
        })
        
        self.generic_visit(node)

    def visit_AsyncFunctionDef(self, node):
        self.visit_FunctionDef(node)
        
    def visit_ClassDef(self, node):
        self.classes.append(node.name)
        self.register_name(node.name, 'class')
        if node.bases:
            for base in node.bases:
                if isinstance(base, ast.Name) and base.id not in ('object', 'Exception'):
                    self.oop['inheritance_count'] += 1
                elif isinstance(base, ast.Name) and base.id == 'Exception':
                    self.error_handling['custom_exceptions'] += 1
        self.generic_visit(node)
        
    def visit_Import(self, node):
        for alias in node.names:
            self.imports.append(alias.name.split('.')[0])
            if alias.asname:
                self.import_habits['aliased'] += 1
        self.generic_visit(node)
        
    def visit_ImportFrom(self, node):
        self.import_habits['from_import'] += 1
        if node.level > 0:
            self.import_habits['relative'] += 1
        if node.module:
            self.imports.append(node.module.split('.')[0])
        for alias in node.names:
            if alias.asname:
                self.import_habits['aliased'] += 1
        self.generic_visit(node)
        
    def visit_Assign(self, node):
        for target in node.targets:
            if isinstance(target, ast.Name):
                self.register_name(target.id, 'variable')
        self.generic_visit(node)
        
    def visit_AnnAssign(self, node):
        self.ast_structures['type_hints'] += 1
        if isinstance(node.target, ast.Name):
            self.register_name(node.target.id, 'variable')
        self.generic_visit(node)

    def visit_If(self, node):
        self.control_flow['if'] += 1
        try:
            if isinstance(node.test, ast.Compare) and isinstance(node.test.left, ast.Name) and node.test.left.id == '__name__':
                self.idioms['name_main'] += 1
        except Exception:
            pass  # Safe to ignore - idiom detection is non-critical
        self.generic_visit(node)
        
    def visit_Compare(self, node):
        for op, comp in zip(node.ops, node.comparators):
            if isinstance(op, (ast.Is, ast.IsNot)) and isinstance(comp, ast.Constant) and comp.value is None:
                self.idioms['is_none'] += 1
        self.generic_visit(node)

    def visit_For(self, node): self.control_flow['for'] += 1; self.generic_visit(node)
    def visit_While(self, node): self.control_flow['while'] += 1; self.generic_visit(node)
    def visit_Try(self, node): self.control_flow['try'] += 1; self.generic_visit(node)
    def visit_Break(self, node): self.control_flow['break'] += 1; self.generic_visit(node)
    def visit_Continue(self, node): self.control_flow['continue'] += 1; self.generic_visit(node)
    def visit_Yield(self, node): self.control_flow['yield'] += 1; self.generic_visit(node)
    def visit_YieldFrom(self, node): self.control_flow['yield'] += 1; self.generic_visit(node)
    def visit_Await(self, node): self.control_flow['await'] += 1; self.generic_visit(node)
    def visit_Raise(self, node): self.error_handling['raise'] += 1; self.generic_visit(node)
    def visit_ListComp(self, node): self.ast_structures['list_comp'] += 1; self.generic_visit(node)
    def visit_DictComp(self, node): self.ast_structures['dict_comp'] += 1; self.generic_visit(node)
    def visit_Lambda(self, node): self.ast_structures['lambda'] += 1; self.generic_visit(node)
    
    def visit_Call(self, node):
        if isinstance(node.func, ast.Name) and node.func.id == 'super':
            self.oop['super_calls'] += 1
        self.generic_visit(node)


def analyze_python_file(filepath: str, content: str) -> Dict:
    metrics = {
        "functions": 0, "classes": 0, "imports": [], "names": [],
        "function_lengths": [], "complexities": [], "docstrings": 0,
        "identifier_lengths": [], "nesting_depths": [],
        "control_flow": {}, "ast_structures": {}, "error_handling": {},
        "oop": {}, "import_habits": {}, "idioms": {}, "function_details": []
    }
    try:
        tree = ast.parse(content)
        visitor = PythonVisitor()
        visitor.visit(tree)
        metrics["functions"] = len(visitor.functions)
        metrics["classes"] = len(visitor.classes)
        metrics["imports"] = visitor.imports
        metrics["names"] = visitor.names
        metrics["function_lengths"] = visitor.function_lengths
        metrics["complexities"] = visitor.complexity_scores
        metrics["identifier_lengths"] = visitor.identifier_lengths
        metrics["nesting_depths"] = visitor.nesting_depths
        metrics["control_flow"] = visitor.control_flow
        metrics["ast_structures"] = visitor.ast_structures
        metrics["error_handling"] = visitor.error_handling
        metrics["oop"] = visitor.oop
        metrics["import_habits"] = visitor.import_habits
        metrics["idioms"] = visitor.idioms
        metrics["function_details"] = visitor.function_details
        
        for node in ast.walk(tree):
            if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef, ast.Module)):
                if ast.get_docstring(node):
                    metrics["docstrings"] += 1
    except Exception:
        pass
    return metrics

def analyze_js_ts_file(filepath: str, content: str, lines: List[str]) -> Dict:
    metrics = {
        "functions": 0, "classes": 0, "imports": [], "names": [],
        "function_lengths": [], "complexities": [], "docstrings": 0,
        "identifier_lengths": [], "nesting_depths": [],
        "control_flow": {'if': 0, 'for': 0, 'while': 0, 'try': 0, 'break': 0, 'continue': 0, 'yield': 0, 'await': 0},
        "ast_structures": {'list_comp': 0, 'dict_comp': 0, 'lambda': 0, 'decorators': 0, 'type_hints': 0},
        "error_handling": {'raise': 0, 'custom_exceptions': 0},
        "oop": {'inheritance_count': 0, 'super_calls': 0, 'static_methods': 0, 'class_methods': 0},
        "import_habits": {'aliased': 0, 'from_import': 0, 'relative': 0},
        "idioms": {'is_none': 0, 'name_main': 0},
        "function_details": []
    }
    in_function = False
    func_start = 0
    bracket_level = 0
    max_nesting = 0
    
    for i, line in enumerate(lines):
        line = line.strip()
        if line.startswith("import ") or "require(" in line:
            parts = line.split()
            for p in parts:
                if p.startswith("'") or p.startswith('"'):
                    metrics["imports"].append(p.strip("'\"").split('/')[0])
                    
        if "function " in line or "=>" in line:
            metrics["functions"] += 1
            if not in_function and "{" in line:
                in_function = True
                func_start = i
                bracket_level = line.count("{") - line.count("}")
                max_nesting = max(max_nesting, bracket_level)
        elif line.startswith("class "):
            metrics["classes"] += 1
            if "extends " in line:
                metrics["oop"]["inheritance_count"] += 1
            
        if in_function:
            bracket_level += line.count("{") - line.count("}")
            max_nesting = max(max_nesting, bracket_level)
            if bracket_level <= 0:
                length = i - func_start + 1
                metrics["function_lengths"].append(length)
                metrics["nesting_depths"].append(max_nesting)
                metrics["function_details"].append({"name": "anonymous_or_js_func", "line": func_start+1, "length": length, "complexity": 1})
                in_function = False
                max_nesting = 0
                
        if line.startswith("if ("): metrics["control_flow"]["if"] += 1
        if line.startswith("for ("): metrics["control_flow"]["for"] += 1
        if line.startswith("while ("): metrics["control_flow"]["while"] += 1
        if "try {" in line: metrics["control_flow"]["try"] += 1
        if "await " in line: metrics["control_flow"]["await"] += 1
        if "throw " in line: metrics["error_handling"]["raise"] += 1
        if "super(" in line: metrics["oop"]["super_calls"] += 1

        if any(kw in line for kw in ["if (", "for (", "while (", "catch (", "?", "&&", "||"]):
            metrics["complexities"].append(1)
            
    return metrics

def analyze_file(filepath: str) -> Dict[str, Any]:
    ext = os.path.splitext(filepath)[1].lower()
    lang = CODE_EXTENSIONS.get(ext, 'unknown')
    
    metrics = {
        "lang": lang, "bytes": os.path.getsize(filepath), "loc": 0,
        "functions": 0, "classes": 0, "imports": [],
        "function_lengths": [], "complexities": [], "names": [], 
        "identifier_lengths": [], "nesting_depths": [],
        "control_flow": {'if': 0, 'for': 0, 'while': 0, 'try': 0, 'break': 0, 'continue': 0, 'yield': 0, 'await': 0},
        "ast_structures": {'list_comp': 0, 'dict_comp': 0, 'lambda': 0, 'decorators': 0, 'type_hints': 0},
        "error_handling": {'raise': 0, 'custom_exceptions': 0},
        "oop": {'inheritance_count': 0, 'super_calls': 0, 'static_methods': 0, 'class_methods': 0},
        "import_habits": {'aliased': 0, 'from_import': 0, 'relative': 0},
        "idioms": {'is_none': 0, 'name_main': 0},
        "docstrings": 0, "comment_lines": 0, "inline_comments": 0, "block_comments": 0,
        "todos": 0, "bare_excepts": 0, "evals": 0, "secrets": 0, "ai_patterns": 0,
        "spaces_indent": 0, "tabs_indent": 0, "trailing_ws": 0,
        "single_quotes": 0, "double_quotes": 0, "magic_numbers": 0,
        "function_details": []
    }
    
    if lang == 'unknown': return metrics

    # Skip oversized files (minified bundles, generated code, etc.)
    if os.path.getsize(filepath) > MAX_FILE_BYTES:
        return metrics

    try:
        with open(filepath, 'r', encoding='utf-8', errors='ignore') as f:
            content = f.read()
            lines = content.split('\n')
            metrics["loc"] = len(lines)
            
            metrics["todos"] = len(RE_TODO.findall(content))
            metrics["bare_excepts"] = len(RE_BARE_EXCEPT.findall(content))
            metrics["evals"] = len(RE_EVAL.findall(content))
            metrics["secrets"] = len(RE_SECRET.findall(content))
            metrics["ai_patterns"] = len(RE_AI_PATTERN.findall(content))
            metrics["single_quotes"] = content.count("'")
            metrics["double_quotes"] = content.count('"')
            
            in_block_comment = False
            for line in lines:
                sline = line.lstrip()
                if not sline: continue
                
                if ext in ['.js', '.ts', '.java', '.c', '.cpp', '.cs']:
                    if sline.startswith('/*'): in_block_comment = True
                    if in_block_comment:
                        metrics["block_comments"] += 1
                        if '*/' in sline: in_block_comment = False
                        continue
                    if sline.startswith('//'): metrics["comment_lines"] += 1; metrics["inline_comments"] += 1
                elif ext == '.py':
                    if sline.startswith('#'): metrics["comment_lines"] += 1; metrics["inline_comments"] += 1
                    
                indent = line[:len(line) - len(sline)]
                if '\t' in indent: metrics["tabs_indent"] += 1
                elif ' ' in indent: metrics["spaces_indent"] += 1
                    
                if line.endswith(' ') or line.endswith('\t'): metrics["trailing_ws"] += 1
                if re.search(r'\b\d{2,}\b', sline): metrics["magic_numbers"] += 1
            
            if ext == '.py':
                py_metrics = analyze_python_file(filepath, content)
                for k in py_metrics:
                    if isinstance(metrics.get(k), dict):
                        for sub_k in py_metrics[k]: metrics[k][sub_k] += py_metrics[k][sub_k]
                    elif isinstance(metrics.get(k), list): metrics[k].extend(py_metrics[k])
                    else: metrics[k] += py_metrics[k]
            elif ext in ['.js', '.jsx', '.ts', '.tsx', '.mjs', '.cjs', '.java', '.c', '.cpp', '.cc', '.h', '.hpp', '.cs', '.go', '.rs']:
                try:
                    from .ml_engine.cross_language_parser import parse_universal_file
                except Exception:
                    from ml_engine.cross_language_parser import parse_universal_file
                u_metrics = parse_universal_file(filepath, content)
                for k in u_metrics:
                    if k in ["lang", "bytes"]:
                        continue
                    if isinstance(metrics.get(k), dict):
                        for sub_k in u_metrics[k]:
                            metrics[k][sub_k] = metrics[k].get(sub_k, 0) + u_metrics[k][sub_k]
                    elif isinstance(metrics.get(k), list):
                        metrics[k].extend(u_metrics[k])
                    elif k in metrics:
                        metrics[k] += u_metrics[k]
                
    except Exception as e:
        print(f"Error analyzing file {filepath}: {e}")
        pass
        
    return metrics

def build_repository_codedna(repo_dir: str) -> Dict[str, Any]:
    dna = {
        "repo_count_usable_files_languages": {"total_repos": 0, "usable_files": 0, "languages": {}},
        "loc_distribution": {}, "file_size_distribution": {},
        "function_class_distribution": {}, "dependency_library_fingerprint": {"all": []},
        "framework_fingerprint": [], "architecture_fingerprint": [],
        "code_quality_error_patterns": {"todos": 0, "bare_excepts": 0, "evals": 0, "secrets": 0, "magic_numbers": 0, "ai_patterns": 0},
        "comment_docstring_patterns": {"comment_lines": 0, "docstrings": 0, "comment_to_code_ratio": 0.0},
        "naming_convention_distribution": {"snake_case": 0, "camelCase": 0, "PascalCase": 0, "UPPER_CASE": 0, "other": 0},
        "formatting_indentation_fingerprint": {"spaces_indent": 0, "tabs_indent": 0, "trailing_ws": 0, "single_quotes": 0, "double_quotes": 0},
        "complexity_distribution": {}, "historical_consistency_score": 0.0, "baseline_reliability_score": 0.0,
        "identifier_length_distribution": {}, "nesting_depth_distribution": {},
        "control_flow_patterns": {'if': 0, 'for': 0, 'while': 0, 'try': 0, 'break': 0, 'continue': 0, 'yield': 0, 'await': 0},
        "ast_structural_patterns": {'list_comp': 0, 'dict_comp': 0, 'lambda': 0, 'decorators': 0, 'type_hints': 0},
        "error_handling_patterns": {'raise': 0, 'custom_exceptions': 0, 'bare_excepts': 0},
        "abstraction_level": {"type_hint_ratio": 0.0, "static_methods": 0, "class_methods": 0},
        "oop_composition_inheritance_tendencies": {'inheritance_count': 0, 'super_calls': 0, 'class_to_func_ratio': 0.0},
        "import_dependency_habits": {'aliased': 0, 'from_import': 0, 'relative': 0},
        "comment_style": {"inline_comments": 0, "block_comments": 0},
        "repeated_coding_idioms": {'is_none': 0, 'name_main': 0},
        "codedna_similarity_score": 0.0,
        "historical_variance_confidence": "HIGH",
        "file_metrics": [] 
    }
    
    all_loc, all_bytes, all_function_lengths, all_complexities = [], [], [], []
    all_identifier_lengths, all_nesting_depths = [], []
    funcs_per_file, classes_per_file, all_imports = [], [], []
    
    if os.path.exists(repo_dir):
        dna["repo_count_usable_files_languages"]["total_repos"] = len([d for d in os.listdir(repo_dir) if os.path.isdir(os.path.join(repo_dir, d))])
        for root, dirs, files in os.walk(repo_dir):
            dirs[:] = [d for d in dirs if d not in EXCLUDE_DIRS]
            for file in files:
                filepath = os.path.join(root, file)
                if not is_usable_file(filepath): continue
                if os.path.splitext(file)[1].lower() not in CODE_EXTENSIONS: continue

                # Hard cap — prevent processing enormous repos
                if dna["repo_count_usable_files_languages"]["usable_files"] >= MAX_FILES_PER_REPO:
                    break

                dna["repo_count_usable_files_languages"]["usable_files"] += 1
                
                m = analyze_file(filepath)
                m["filepath"] = os.path.relpath(filepath, repo_dir)
                dna["file_metrics"].append(m)
                
                lang = m["lang"]
                dna["repo_count_usable_files_languages"]["languages"][lang] = dna["repo_count_usable_files_languages"]["languages"].get(lang, 0) + 1
                
                all_loc.append(m["loc"])
                all_bytes.append(m["bytes"])
                all_function_lengths.extend(m["function_lengths"])
                all_identifier_lengths.extend(m["identifier_lengths"])
                all_nesting_depths.extend(m["nesting_depths"])
                
                if m["complexities"]:
                    all_complexities.extend(m["complexities"])
                        
                funcs_per_file.append(m["functions"])
                classes_per_file.append(m["classes"])
                all_imports.extend(m["imports"])
                
                for k in ["todos", "bare_excepts", "evals", "secrets", "magic_numbers", "ai_patterns"]:
                    dna["code_quality_error_patterns"][k] += m[k]
                dna["error_handling_patterns"]["bare_excepts"] += m["bare_excepts"]
                
                dna["comment_docstring_patterns"]["comment_lines"] += m["comment_lines"]
                dna["comment_docstring_patterns"]["docstrings"] += m["docstrings"]
                dna["comment_style"]["inline_comments"] += m["inline_comments"]
                dna["comment_style"]["block_comments"] += m["block_comments"]
                
                for k in ["spaces_indent", "tabs_indent", "trailing_ws", "single_quotes", "double_quotes"]:
                    dna["formatting_indentation_fingerprint"][k] += m[k]
                    
                for name, ntype in m["names"]:
                    dna["naming_convention_distribution"][classify_name(name)] += 1
                    
                for dict_key in ["control_flow", "ast_structures", "error_handling", "oop", "import_habits", "idioms"]:
                    target_key = dict_key + "_patterns" if dict_key in ["control_flow", "error_handling"] else dict_key
                    if target_key == "ast_structures": target_key = "ast_structural_patterns"
                    elif target_key == "oop": target_key = "oop_composition_inheritance_tendencies"
                    elif target_key == "import_habits": target_key = "import_dependency_habits"
                    elif target_key == "idioms": target_key = "repeated_coding_idioms"
                    
                    for k, v in m[dict_key].items():
                        if k in dna[target_key]:
                            dna[target_key][k] += v
                        elif k in dna.get("abstraction_level", {}):
                            dna["abstraction_level"][k] += v
                            
    dna["loc_distribution"] = compute_stats(all_loc)
    dna["file_size_distribution"] = compute_stats(all_bytes)
    dna["identifier_length_distribution"] = compute_stats(all_identifier_lengths)
    dna["nesting_depth_distribution"] = compute_stats(all_nesting_depths)
    
    total_loc = dna["loc_distribution"]["total"]
    dna["comment_docstring_patterns"]["comment_to_code_ratio"] = (dna["comment_docstring_patterns"]["comment_lines"] / total_loc) if total_loc > 0 else 0
    
    tot_funcs = sum(funcs_per_file)
    tot_classes = sum(classes_per_file)
    dna["function_class_distribution"] = {
        "total_functions": tot_funcs, "total_classes": tot_classes,
        "functions_per_file": compute_stats(funcs_per_file), "classes_per_file": compute_stats(classes_per_file),
        "function_length_distribution": compute_stats(all_function_lengths)
    }
    
    if tot_funcs > 0:
        dna["oop_composition_inheritance_tendencies"]["class_to_func_ratio"] = tot_classes / tot_funcs
        
    if dna["ast_structural_patterns"]["type_hints"] > 0:
        dna["abstraction_level"]["type_hint_ratio"] = dna["ast_structural_patterns"]["type_hints"] / max(1, tot_funcs)
    
    dna["complexity_distribution"] = compute_stats(all_complexities)
    uniq_imports = list(set(all_imports))
    dna["dependency_library_fingerprint"]["all"] = uniq_imports
    
    frameworks = []
    if any(i in uniq_imports for i in ['fastapi', 'flask', 'django']): frameworks.append('Python Web')
    if any(i in uniq_imports for i in ['react', 'next', 'vue']): frameworks.append('Frontend JS/TS')
    dna["framework_fingerprint"] = frameworks
    
    if len(frameworks) > 1: dna["architecture_fingerprint"].append('Multi-stack/Modular')
    elif dna["repo_count_usable_files_languages"]["usable_files"] < 5: dna["architecture_fingerprint"].append('Script-based')
    else: dna["architecture_fingerprint"].append('Monolith')

    files_count = dna["repo_count_usable_files_languages"]["usable_files"]
    reliability = 40 if files_count > 50 else (20 if files_count > 10 else 0)
    if dna["repo_count_usable_files_languages"]["total_repos"] >= 3: reliability += 30
    if total_loc >= 500: reliability += 40
    dna["baseline_reliability_score"] = min(100, reliability)
    
    names = dna["naming_convention_distribution"]
    total_names = sum(names.values())
    if total_names > 0:
        max_style = max(names.values()) / total_names
        if max_style > 0.8: dna["historical_variance_confidence"] = "HIGH"
        elif max_style > 0.5: dna["historical_variance_confidence"] = "MEDIUM"
        else: dna["historical_variance_confidence"] = "LOW"

    return dna

def compare_codedna(baseline_dna: Dict[str, Any], submission_dna: Dict[str, Any], repos_dir: str = "", sub_dir: str = "") -> Dict[str, Any]:
    def calc_dev(b_val, s_val):
        """Non-linear deviation: small natural drifts score low, only extreme outliers score high."""
        if b_val == 0 and s_val == 0: return 0.0
        if b_val == 0: return 60.0  # Appeared from nothing — notable but not catastrophic
        raw_ratio = abs(s_val - b_val) / max(0.1, b_val)
        # Sigmoid-style curve: <20% change → low, 50% → moderate, >100% → high
        # Maps: 0→0, 0.2→15, 0.5→40, 1.0→70, 2.0→90, 3.0→97
        score = 100.0 * (1.0 - 1.0 / (1.0 + (raw_ratio / 0.5) ** 1.4))
        return min(100.0, score)
        
    def dict_dev(b_dict, s_dict):
        devs = []
        for k in set(list(b_dict.keys()) + list(s_dict.keys())):
            devs.append(calc_dev(b_dict.get(k, 0), s_dict.get(k, 0)))
        return sum(devs) / max(1, len(devs))
        
    deviations = {}
    
    deviations["structural_deviation"] = (dict_dev(baseline_dna.get("ast_structural_patterns", {}), submission_dna.get("ast_structural_patterns", {})) +
                                         dict_dev(baseline_dna.get("control_flow_patterns", {}), submission_dna.get("control_flow_patterns", {}))) / 2
    deviations["naming_deviation"] = dict_dev(baseline_dna.get("naming_convention_distribution", {}), submission_dna.get("naming_convention_distribution", {}))
    deviations["formatting_deviation"] = dict_dev(baseline_dna.get("formatting_indentation_fingerprint", {}), submission_dna.get("formatting_indentation_fingerprint", {}))
    
    b_comp = baseline_dna.get("complexity_distribution", {})
    s_comp = submission_dna.get("complexity_distribution", {})
    deviations["complexity_deviation"] = (calc_dev(b_comp.get("mean", 0), s_comp.get("mean", 0)) + calc_dev(b_comp.get("p90", 0), s_comp.get("p90", 0))) / 2
    
    b_arch = set(baseline_dna.get("architecture_fingerprint", []))
    s_arch = set(submission_dna.get("architecture_fingerprint", []))
    # Fix 2: Partial Jaccard distance — overlapping architectures score proportionally, not binary 0/100
    if not b_arch and not s_arch:
        deviations["architecture_deviation"] = 0.0
    else:
        intersection = len(b_arch & s_arch)
        union = len(b_arch | s_arch)
        deviations["architecture_deviation"] = round((1.0 - intersection / max(1, union)) * 100.0, 1)
    
    b_deps = set(baseline_dna.get("dependency_library_fingerprint", {}).get("all", []))
    s_deps = set(submission_dna.get("dependency_library_fingerprint", {}).get("all", []))
    new_deps = s_deps - b_deps
    deviations["dependency_deviation"] = min(100.0, (len(new_deps) / max(1, len(s_deps))) * 100.0)
    
    deviations["abstraction_deviation"] = dict_dev(baseline_dna.get("abstraction_level", {}), submission_dna.get("abstraction_level", {}))
    deviations["comment_style_deviation"] = dict_dev(baseline_dna.get("comment_style", {}), submission_dna.get("comment_style", {}))
    deviations["error_handling_deviation"] = dict_dev(baseline_dna.get("error_handling_patterns", {}), submission_dna.get("error_handling_patterns", {}))

    # Phase 5: Cross-Language AST Normalization Parity
    cross_lang_intel = None
    try:
        from .ml_engine.cross_language_parser import compute_cross_language_parity
    except Exception:
        try:
            from ml_engine.cross_language_parser import compute_cross_language_parity
        except Exception:
            compute_cross_language_parity = None

    if compute_cross_language_parity:
        cross_lang_intel = compute_cross_language_parity(baseline_dna, submission_dna)
        if cross_lang_intel.get("is_cross_language"):
            discount = cross_lang_intel.get("cross_language_penalty_discount", 0.3)
            # Normalize naming & formatting penalties if author adopted target language idioms
            deviations["naming_deviation"] = round(deviations["naming_deviation"] * (1.0 - discount), 1)
            deviations["formatting_deviation"] = round(deviations["formatting_deviation"] * (1.0 - discount * 0.75), 1)

    avg_dev = sum(deviations.values()) / len(deviations)
    deviations["overall_behavioral_stylistic_deviation_score"] = max(0.0, 100.0 - avg_dev)
    
    new_patterns = []
    if new_deps: new_patterns.append(f"New libraries used: {', '.join(list(new_deps)[:5])}")
    for k in ["bare_excepts", "evals", "secrets", "ai_patterns"]:
        if submission_dna.get("code_quality_error_patterns", {}).get(k, 0) > 0 and baseline_dna.get("code_quality_error_patterns", {}).get(k, 0) == 0:
            new_patterns.append(f"Introduced {k} never seen in baseline.")
    deviations["new_unseen_patterns"] = new_patterns
    
    deviations["distribution_shifts"] = {
        "complexity_p90_shift": f"{b_comp.get('p90', 0)} -> {s_comp.get('p90', 0)}",
        "loc_p90_shift": f"{baseline_dna.get('loc_distribution', {}).get('p90', 0)} -> {submission_dna.get('loc_distribution', {}).get('p90', 0)}"
    }

    per_file_scores, per_function_scores, suspicious_regions = [], [], []
    b_p90_comp = b_comp.get("p90", 10)
    b_mean_loc = baseline_dna.get("loc_distribution", {}).get("mean", 50)
    
    for f_metrics in submission_dna.get("file_metrics", []):
        f_score = 0
        if f_metrics.get("loc", 0) > b_mean_loc * 3: f_score += 30
        
        funcs = f_metrics.get("function_details", [])
        for fn in funcs:
            fn_score = 0
            if fn["complexity"] > b_p90_comp * 1.5:
                fn_score += 50
                suspicious_regions.append({
                    "file": f_metrics["filepath"], "line": fn["line"],
                    "reason": f"Function {fn['name']} complexity ({fn['complexity']}) exceeds baseline P90 ({b_p90_comp})"
                })
            if fn_score > 0:
                per_function_scores.append({"file": f_metrics["filepath"], "function": fn["name"], "anomaly_score": fn_score})
                
        f_score += sum(fn["anomaly_score"] for fn in per_function_scores if fn["file"] == f_metrics["filepath"])
        if f_score > 0:
            per_file_scores.append({"file": f_metrics["filepath"], "anomaly_score": min(100, f_score)})
            
    deviations["per_file_anomaly_scores"] = sorted(per_file_scores, key=lambda x: x["anomaly_score"], reverse=True)
    deviations["per_function_anomaly_scores"] = sorted(per_function_scores, key=lambda x: x["anomaly_score"], reverse=True)
    deviations["exact_suspicious_regions_lines"] = suspicious_regions
    
    ranked = sorted([(k, v) for k, v in deviations.items() if k.endswith("_deviation")], key=lambda x: x[1], reverse=True)
    deviations["anomaly_ranking"] = ranked
    
    # --- PHASE 4: Authorship & Similarity Intelligence ---
    
    b_ai_indicators = baseline_dna.get("code_quality_error_patterns", {}).get("ai_patterns", 0)
    s_ai_indicators = submission_dna.get("code_quality_error_patterns", {}).get("ai_patterns", 0)
    
    b_type_hint_ratio = baseline_dna.get("abstraction_level", {}).get("type_hint_ratio", 0)
    s_type_hint_ratio = submission_dna.get("abstraction_level", {}).get("type_hint_ratio", 0)
    sudden_sophistication = "High" if (s_type_hint_ratio > b_type_hint_ratio + 0.5) or (s_comp.get("p90", 0) > b_comp.get("p90", 0) * 1.5) else "Low"
    
    sizes = [f["bytes"] for f in submission_dna.get("file_metrics", [])]
    dupes = len(sizes) - len(set(sizes))
    internal_dupe_ratio = (dupes / len(sizes) * 100) if sizes else 0.0

    b_reliability = baseline_dna.get("baseline_reliability_score", 0)
    
    # Fix 3: AI Author Profile Tiers
    # Tier A: Baseline already has AI patterns AND submission also has them → "Consistent AI Author"
    # Tier B: Baseline is clean BUT submission introduces AI patterns → "Sudden AI Introduction"
    # Tier C: No AI patterns detected in either → "No AI signal"
    baseline_already_ai = b_ai_indicators > 0
    submission_has_ai   = s_ai_indicators > 0 or sudden_sophistication == "High"

    if baseline_already_ai and submission_has_ai:
        ai_author_profile = "Consistent AI Author"
        ai_signals = "High"
        concern_reason = "Both baseline and submission exhibit AI-associated patterns. This student may consistently use AI tools. Deviation from their own baseline is low — investigation should focus on AI policy compliance, not substitution fraud."
    elif not baseline_already_ai and submission_has_ai:
        ai_author_profile = "Sudden AI Introduction"
        ai_signals = "High"
        concern_reason = "Baseline shows no AI patterns, but submission introduces them suddenly. This is a stronger forensic signal of possible substitution."
    elif not baseline_already_ai and not submission_has_ai and deviations["overall_behavioral_stylistic_deviation_score"] < 40:
        ai_author_profile = "Low Evidence"
        ai_signals = "Low"
        concern_reason = "Submission behaviorally matches the baseline. No forensic anomalies detected."
    else:
        ai_author_profile = "Uncertain"
        ai_signals = "Moderate"
        concern_reason = "Partial deviations detected. Insufficient evidence to conclude either way."

    baseline_contamination = "High" if baseline_already_ai else "Low"
    authorship_ev = "Strong" if deviations["overall_behavioral_stylistic_deviation_score"] > 75 else ("Moderate" if deviations["overall_behavioral_stylistic_deviation_score"] > 50 else "Weak")
    
    # Overall concern respects the tiered model
    if ai_author_profile == "Consistent AI Author":
        concern = "Moderate"  # Not "High" — this is a policy question, not substitution
    elif ai_author_profile == "Sudden AI Introduction":
        concern = "High"
    elif authorship_ev == "Weak":
        concern = "Moderate"
    else:
        concern = "Low"

    phase4 = {
        "historical_codedna_similarity": deviations["overall_behavioral_stylistic_deviation_score"],
        "internal_code_duplication": internal_dupe_ratio,
        "cross_repository_similarity": "N/A - Offline Analysis",
        "known_reference_code_similarity": "N/A - Offline Analysis",
        "semantic_similarity": max(0.0, 100.0 - deviations["structural_deviation"]),
        "token_ast_similarity": max(0.0, 100.0 - (deviations["structural_deviation"] * 0.7 + deviations["complexity_deviation"] * 0.3)),
        "novel_code_ratio": deviations["dependency_deviation"],
        "code_reuse_ratio": 100.0 - deviations["dependency_deviation"],
        "ai_pattern_indicators": s_ai_indicators,
        "baseline_ai_pattern_indicators": b_ai_indicators,
        "sudden_sophistication_change": sudden_sophistication,
        "ai_author_profile": ai_author_profile,
        "concern_reason": concern_reason,
        "architectural_discontinuity": "High" if deviations["architecture_deviation"] > 50 else "Low",
        "dependency_discontinuity": "High" if deviations["dependency_deviation"] > 50 else "Low",
        "evidence_confidence_score": b_reliability,
        "baseline_contamination_risk": baseline_contamination,
        "categorical_signals": {
            "ai_associated_signals": ai_signals,
            "authorship_evidence": authorship_ev,
            "baseline_reliability": "High" if b_reliability > 70 else ("Moderate" if b_reliability > 30 else "Low"),
            "overall_investigation_concern": concern
        }
    }
    
    b_naming_pref = max(baseline_dna.get("naming_convention_distribution", {'unknown': 1}), key=baseline_dna.get("naming_convention_distribution", {'unknown': 1}).get, default='unknown')
    s_naming_pref = max(submission_dna.get("naming_convention_distribution", {'unknown': 1}), key=submission_dna.get("naming_convention_distribution", {'unknown': 1}).get, default='unknown')

    deviations["deviation_reasons"] = {
        "structural": "Shift in AST structures & control flow (lists, dicts, loops).",
        "naming": f"Baseline prefers {b_naming_pref} vs Submission prefers {s_naming_pref}.",
        "formatting": "Noticeable changes in indentation (tabs vs spaces) or quote styles.",
        "complexity": f"Mean complexity shifted {b_comp.get('mean', 0):.1f} -> {s_comp.get('mean', 0):.1f}; P90 {b_comp.get('p90', 0):.1f} -> {s_comp.get('p90', 0):.1f}",
        "architecture": f"Baseline {', '.join(b_arch) if b_arch else 'Standard'} vs Submission {', '.join(s_arch) if s_arch else 'Standard'}.",
        "dependency": f"Found {len(new_deps)} completely novel dependency imports.",
        "abstraction": "Shifts in class ratios, static methods, and type-hint density.",
        "baseline_reliability": f"Calculated from {baseline_dna.get('repo_count_usable_files_languages', {}).get('usable_files', 0)} baseline files.",
        "similarity": "Calculated via inverse structural and complexity deviation representing raw semantic overlap."
    }
    
    submission_dna.update(deviations)
    submission_dna["codedna_similarity_score"] = deviations["overall_behavioral_stylistic_deviation_score"]
    
    # --- PHASE 3: ML Intelligence (Siamese Embeddings & Statistical Calibration) ---
    ml_intel = None
    try:
        from .ml_engine import run_hybrid_forensic_analysis
        ml_intel = run_hybrid_forensic_analysis(baseline_dna, submission_dna, deviations)
    except Exception:
        try:
            from ml_engine import run_hybrid_forensic_analysis
            ml_intel = run_hybrid_forensic_analysis(baseline_dna, submission_dna, deviations)
        except Exception as e:
            ml_intel = {"status": "fallback", "error": str(e)}

    # --- PHASE 4: Temporal Evolution & Change-Point Analysis ---
    temporal_intel = None
    try:
        from .ml_engine import analyze_temporal_evolution
        temporal_intel = analyze_temporal_evolution(repos_dir, sub_dir, baseline_dna, submission_dna)
    except Exception:
        try:
            from ml_engine import analyze_temporal_evolution
            temporal_intel = analyze_temporal_evolution(repos_dir, sub_dir, baseline_dna, submission_dna)
        except Exception as e:
            temporal_intel = {"status": "fallback", "error": str(e)}

    return {
        "baseline_metrics": baseline_dna,
        "submission_metrics": submission_dna,
        "forensics": deviations,
        "authorship_intelligence": phase4,
        "ml_intelligence": ml_intel,
        "temporal_intelligence": temporal_intel,
        "cross_language_intelligence": cross_lang_intel
    }


def subtract_template_dna(submission_dna: Dict[str, Any], template_dna: Dict[str, Any]) -> Dict[str, Any]:
    """
    Recursively subtract template DNA from submission DNA.
    Returns a new DNA dictionary with template contributions removed.
    """
    result = {}
    all_keys = set(submission_dna.keys()) | set(template_dna.keys())
    for key in all_keys:
        sub_val = submission_dna.get(key)
        tmpl_val = template_dna.get(key)
        # If key only in submission, keep as is
        if tmpl_val is None:
            result[key] = sub_val
            continue
        # If key only in template, treat submission as zero/empty
        if sub_val is None:
            if isinstance(tmpl_val, (int, float)):
                result[key] = 0
            elif isinstance(tmpl_val, dict):
                result[key] = {}
            elif isinstance(tmpl_val, list):
                result[key] = []
            else:
                # Try to create an empty instance of the same type
                try:
                    result[key] = type(tmpl_val)()
                except Exception:
                    result[key] = None
            continue
        # Both present
        if isinstance(sub_val, (int, float)) and isinstance(tmpl_val, (int, float)):
            result[key] = sub_val - tmpl_val
        elif isinstance(sub_val, dict) and isinstance(tmpl_val, dict):
            result[key] = subtract_template_dna(sub_val, tmpl_val)
        elif isinstance(sub_val, list) and isinstance(tmpl_val, list):
            # Handle list of strings: set difference (submission - template)
            if all(isinstance(x, str) for x in sub_val) and all(isinstance(x, str) for x in tmpl_val):
                result[key] = [x for x in sub_val if x not in tmpl_val]
            # Handle list of numbers: element-wise subtraction (if same length)
            elif all(isinstance(x, (int, float)) for x in sub_val) and all(isinstance(x, (int, float)) for x in tmpl_val):
                if len(sub_val) == len(tmpl_val):
                    result[key] = [a - b for a, b in zip(sub_val, tmpl_val)]
                else:
                    # If lengths differ, pad shorter with zeros? We'll just keep submission as is.
                    result[key] = sub_val.copy()
            else:
                # Mixed or unknown list type: keep submission
                result[key] = sub_val.copy()
        else:
            # For other types (e.g., string, bool), keep submission (assuming template should not affect)
            result[key] = sub_val
    return result


def build_cohort_codedna(cohort_dirs: List[str]) -> Dict[str, Any]:
    """
    Build cohort DNA from multiple student submission directories.
    Computes aggregate statistics (P50, P75, P90, IQR) across students for each metric.
    """
    if not cohort_dirs:
        return build_repository_codedna("")  # Return empty DNA

    # Collect individual student DNAs
    student_dnas = []
    for cohort_dir in cohort_dirs:
        if os.path.exists(cohort_dir):
            dna = build_repository_codedna(cohort_dir)
            student_dnas.append(dna)

    if not student_dnas:
        return build_repository_codedna("")

    # Use the first student's DNA as a template for structure
    cohort_dna = copy.deepcopy(student_dnas[0])

    # We'll aggregate numeric metrics that are scalars or nested scalars
    # For simplicity, we'll focus on the key metrics that are used in comparisons:
    # loc_distribution, file_size_distribution, identifier_length_distribution, nesting_depth_distribution,
    # complexity_distribution, and the various _distribution keys in the DNA.
    # We'll also aggregate the counts and sums where appropriate.

    # Helper to collect values for a given path in the DNA
    def collect_values(dnas: List[Dict], path: List[str]) -> List[float]:
        vals = []
        for dna in dnas:
            try:
                ref = dna
                for p in path:
                    if isinstance(ref, dict):
                        ref = ref.get(p)
                    else:
                        ref = None
                        break
                if ref is not None and isinstance(ref, (int, float)):
                    vals.append(float(ref))
                elif isinstance(ref, dict):
                    # If we reach a dict, we might want to collect its values? We'll skip for now.
                    pass
            except Exception:
                pass
        return vals

    # Helper to set a value in the DNA at a given path
    def set_value(dna: Dict, path: List[str], value: Any):
        ref = dna
        for p in path[:-1]:
            if isinstance(ref, dict):
                ref = ref.setdefault(p, {})
            else:
                return
        last = path[-1]
        if isinstance(ref, dict):
            ref[last] = value

    # Define the numeric scalar paths we want to aggregate
    numeric_paths = [
        ["loc_distribution", "mean"],
        ["loc_distribution", "p50"],
        ["loc_distribution", "p75"],
        ["loc_distribution", "p90"],
        ["file_size_distribution", "mean"],
        ["file_size_distribution", "p50"],
        ["file_size_distribution", "p75"],
        ["file_size_distribution", "p90"],
        ["identifier_length_distribution", "mean"],
        ["identifier_length_distribution", "p50"],
        ["identifier_length_distribution", "p75"],
        ["identifier_length_distribution", "p90"],
        ["nesting_depth_distribution", "mean"],
        ["nesting_depth_distribution", "p50"],
        ["nesting_depth_distribution", "p75"],
        ["nesting_depth_distribution", "p90"],
        ["complexity_distribution", "mean"],
        ["complexity_distribution", "p50"],
        ["complexity_distribution", "p75"],
        ["complexity_distribution", "p90"],
        ["code_quality_error_patterns", "todos"],
        ["code_quality_error_patterns", "bare_excepts"],
        ["code_quality_error_patterns", "evals"],
        ["code_quality_error_patterns", "secrets"],
        ["code_quality_error_patterns", "magic_numbers"],
        ["code_quality_error_patterns", "ai_patterns"],
        ["comment_docstring_patterns", "comment_lines"],
        ["comment_docstring_patterns", "docstrings"],
        ["formatting_indentation_fingerprint", "spaces_indent"],
        ["formatting_indentation_fingerprint", "tabs_indent"],
        ["formatting_indentation_fingerprint", "trailing_ws"],
        ["formatting_indentation_fingerprint", "single_quotes"],
        ["formatting_indentation_fingerprint", "double_quotes"],
        ["naming_convention_distribution", "snake_case"],
        ["naming_convention_distribution", "camelCase"],
        ["naming_convention_distribution", "PascalCase"],
        ["naming_convention_distribution", "UPPER_CASE"],
        ["naming_convention_distribution", "other"],
        ["oop_composition_inheritance_tendencies", "inheritance_count"],
        ["oop_composition_inheritance_tendencies", "super_calls"],
        ["oop_composition_inheritance_tendencies", "class_to_func_ratio"],
        ["abstraction_level", "type_hint_ratio"],
        ["repeated_coding_idioms", "is_none"],
        ["repeated_coding_idioms", "name_main"],
    ]

    # For each numeric path, collect values from all students and compute statistics
    for path in numeric_paths:
        values = collect_values(student_dnas, path)
        if values:
            stats = compute_stats(values)
            # We'll store the aggregated stats in the cohort DNA at the same path
            # For simplicity, we'll store the mean as the representative value, and also store p50, p75, p90 if the path ends with a distribution key?
            # Actually, the cohort DNA should have distribution statistics itself.
            # We'll change approach: instead of trying to fit into the existing DNA structure,
            # we will compute the cohort DNA by aggregating the raw data from each student's file_metrics?
            # That would be more accurate but much more complex.
            # Given time, we'll store the aggregated statistics as the cohort DNA's values for these keys.
            # We'll set the cohort DNA's value at this path to the mean of the values.
            set_value(cohort_dna, path, stats["mean"])
            # Also store p50, p75, p90 if we want to keep distribution? We'll skip for now.

    # For the file_metrics, we cannot easily aggregate. We'll leave the cohort DNA's file_metrics as empty
    # or we could try to merge? We'll set to empty list.
    cohort_dna["file_metrics"] = []

    # For the repo_count_usable_files_languages, we'll sum the usable_files and languages
    total_usable = sum(d.get("repo_count_usable_files_languages", {}).get("usable_files", 0) for d in student_dnas)
    cohort_dna["repo_count_usable_files_languages"]["usable_files"] = total_usable
    # Merge language counts
    lang_counts = {}
    for d in student_dnas:
        langs = d.get("repo_count_usable_files_languages", {}).get("languages", {})
        for lang, count in langs.items():
            lang_counts[lang] = lang_counts.get(lang, 0) + count
    cohort_dna["repo_count_usable_files_languages"]["languages"] = lang_counts

    # For other fields like dependencies, we'll union
    all_imports = set()
    for d in student_dnas:
        imports = d.get("dependency_library_fingerprint", {}).get("all", [])
        all_imports.update(imports)
    cohort_dna["dependency_library_fingerprint"]["all"] = list(all_imports)

    # For frameworks, we'll union
    all_frameworks = set()
    for d in student_dnas:
        frameworks = d.get("framework_fingerprint", [])
        all_frameworks.update(frameworks)
    cohort_dna["framework_fingerprint"] = list(all_frameworks)

    # Recompute architecture_fingerprint based on frameworks and file count
    frameworks = cohort_dna["framework_fingerprint"]
    if any(i in frameworks for i in ['fastapi', 'flask', 'django']):
        cohort_dna["framework_fingerprint"] = ['Python Web'] if 'Python Web' not in frameworks else frameworks
    if any(i in frameworks for i in ['react', 'next', 'vue']):
        cohort_dna["framework_fingerprint"] = ['Frontend JS/TS'] if 'Frontend JS/TS' not in frameworks else frameworks
    # Architecture fingerprint logic simplified
    if len(frameworks) > 1:
        cohort_dna["architecture_fingerprint"] = ['Multi-stack/Modular']
    elif total_usable < 5:
        cohort_dna["architecture_fingerprint"] = ['Script-based']
    else:
        cohort_dna["architecture_fingerprint"] = ['Monolith']

    # Recompute baseline reliability score (simplified)
    reliability = 40 if total_usable > 50 else (20 if total_usable > 10 else 0)
    if len(student_dnas) > 2:
        reliability += 30
    # We don't have total_loc easily, so we'll skip that part
    cohort_dna["baseline_reliability_score"] = min(100, reliability)

    return cohort_dna
