#!/usr/bin/env python3
"""
Test Data Generator for Phase 3 Extreme Automated Testing
Generates baseline.zip and submission.zip pairs for 8 test scenarios:
1. Clean Student
2. Sudden AI
3. Consistent AI
4. Plagiarism
5. Empty Repo
6. Cross-Language
7. Sophisticated Evasion
8. Template Subtraction
"""

import os
import zipfile
import shutil
from pathlib import Path

def create_clean_student_scenario():
    """Scenario 1: Clean Student - Minor natural evolution"""
    print("Generating Clean Student scenario...")

    # Baseline: Simple calculator with basic functions
    baseline_content = '''def add(a, b):
    """Add two numbers"""
    return a + b

def subtract(a, b):
    """Subtract two numbers"""
    return a - b

def multiply(a, b):
    """Multiply two numbers"""
    return a * b

def calculate_total(items):
    """Calculate total of items"""
    total = 0
    for item in items:
        total += add(item, 0)  # Using add function
    return total

if __name__ == "__main__":
    numbers = [1, 2, 3, 4, 5]
    total = calculate_total(numbers)
    print(f"Total: {total}")
'''

    # Submission: Same structure, minor improvements and natural evolution
    submission_content = '''def add(a, b):
    """Add two numbers and return the result"""
    # Simple addition operation
    return a + b

def subtract(a, b):
    """Subtract two numbers and return the result"""
    return a - b

def multiply(a, b):
    """Multiply two numbers and return the result"""
    return a * b

def calculate_total(items):
    """Calculate total of items in the list"""
    total = 0
    for item in items:
        total = add(total, item)  # Improved: using add function properly
    return total

def process_data(data_list):
    """Process a list of data - new helper function"""
    if not data_list:
        return []
    return [x * 2 for x in data_list]  # Simple processing

if __name__ == "__main__":
    numbers = [1, 2, 3, 4, 5]
    total = calculate_total(numbers)
    processed = process_data(numbers)
    print(f"Total: {total}")
    print(f"Processed: {processed}")
'''

    create_zip_scenario("1_clean", baseline_content, submission_content)

def create_sudden_ai_scenario():
    """Scenario 2: Sudden AI - Clear introduction of AI patterns"""
    print("Generating Sudden AI scenario...")

    # Baseline: Human-written style with natural variations
    baseline_content = '''def calculate_average(numbers):
    """Calculate average of number list"""
    if len(numbers) == 0:
        return 0
    total = 0
    for n in numbers:
        total += n
    return total / len(numbers)

def main():
    # Test data
    test_scores = [85, 92, 78, 96, 88]
    average = calculate_average(test_scores)
    print(f"Average score: {average}")

if __name__ == "__main__":
    main()
'''

    # Submission: Clear AI patterns - comments like "As an AI", overly generic, structured
    submission_content = '''# As an AI, I need to calculate averages efficiently and accurately
def calculate_average(numbers):
    """
    As an AI assistant, I calculate the arithmetic mean of a list of numbers.
    This function handles edge cases and provides precise results.
    """
    # Handle edge case: empty list
    if len(numbers) == 0:
        return 0

    # Initialize sum accumulator
    total = 0

    # Iterate through each number to calculate sum
    for n in numbers:
        total += n

    # Calculate and return average
    return total / len(numbers)

def main():
    # Define test data for validation
    test_scores = [85, 92, 78, 96, 88]

    # Calculate average using AI-optimized function
    average = calculate_average(test_scores)

    # Output formatted result
    print(f"Average score: {average}")

# Standard Python module execution pattern
if __name__ == "__main__":
    main()
'''

    create_zip_scenario("2_sudden_ai", baseline_content, submission_content)

def create_consistent_ai_scenario():
    """Scenario 3: Consistent AI - Baseline already has AI patterns"""
    print("Generating Consistent AI scenario...")

    # Baseline: Already shows AI patterns from the start
    baseline_content = '''# As an AI, I generated this function to process customer data
def process_customer_data(customers):
    """
    As an AI system, I process customer data to extract insights.
    This function was generated by AI for customer analytics.
    """
    if not customers:
        return []

    # Process each customer record
    processed = []
    for customer in customers:
        # Extract relevant fields as an AI would do
        if isinstance(customer, dict) and 'name' in customer:
            processed.append({
                'name': customer['name'].strip(),
                'length': len(customer['name'])
            })
    return processed

# Generated by AI for customer relationship management
if __name__ == "__main__":
    sample_customers = [
        {'name': ' Alice ', 'age': 25},
        {'name': 'Bob', 'age': 30},
        {'name': ' Charlie ', 'age': 35}
    ]
    result = process_customer_data(sample_customers)
    print(f"Processed {len(result)} customers")
'''

    # Submission: Continues with similar AI patterns, showing consistency
    submission_content = '''# As an AI, I enhanced the customer data processing function
def process_customer_data(customers):
    """
    As an AI system, I process customer data to extract insights and analytics.
    Enhanced version with additional validation and logging capabilities.
    Generated by AI for consistent customer analytics.
    """
    # Handle edge case: None or empty input
    if not customers:
        return []

    # Process each customer record with validation
    processed = []
    for customer in customers:
        # Validate customer structure as an AI would do
        if isinstance(customer, dict) and 'name' in customer:
            name = customer['name'].strip() if customer['name'] else ''
            if name:  # Only process non-empty names
                processed.append({
                    'name': name,
                    'length': len(name),
                    'normalized': name.lower()  # Additional AI enhancement
                })
    return processed

# Enhanced by AI with additional validation features
if __name__ == "__main__":
    sample_customers = [
        {'name': ' Alice ', 'age': 25},
        {'name': 'Bob', 'age': 30},
        {'name': ' Charlie ', 'age': 35},
        {'name': '', 'age': 40},  # Edge case: empty name
        {'name': '  ', 'age': 45}  # Edge case: whitespace only
    ]
    result = process_customer_data(sample_customers)
    print(f"Processed {len(result)} valid customers")
    for customer in result:
        print(f"  - {customer['name']} (length: {customer['length']})")
'''

    create_zip_scenario("3_consistent_ai", baseline_content, submission_content)

def create_plagiarism_scenario():
    """Scenario 4: Plagiarism - High concern due to copied structure"""
    print("Generating Plagiarism scenario...")

    # Baseline: Original algorithm implementation with unique structure
    baseline_content = '''def find_largest_palindrome(text):
    """Find the largest palindrome substring in given text"""
    if not text:
        return ""

    max_palindrome = ""
    n = len(text)

    # Check all substrings
    for i in range(n):
        for j in range(i + 1, n + 1):
            substring = text[i:j]
            if substring == substring[::-1]:  # Palindrome check
                if len(substring) > len(max_palindrome):
                    max_palindrome = substring

    return max_palindrome

def is_palindrome(s):
    """Check if string is palindrome"""
    return s == s[::-1]

def main():
    test_string = "babad"
    result = find_largest_palindrome(test_string)
    print(f"Largest palindrome in '{test_string}': '{result}'")

if __name__ == "__main__":
    main()
'''

    # Submission: Nearly identical with only superficial variable name changes
    submission_content = '''def find_largest_palindrome(text):
    """Find the largest palindrome substring in given text"""
    if not text:
        return ""

    max_pal = ""  # Renamed variable
    n = len(text)

    # Check all substrings
    for i in range(n):
        for j in range(i + 1, n + 1):
            substr = text[i:j]  # Renamed variable
            if substr == substr[::-1]:  # Same logic, different var names
                if len(substr) > len(max_pal):
                    max_pal = substr

    return max_pal

def is_palindrome(s):
    """Check if string is palindrome"""
    return s == s[::-1]

def main():
    test_string = "babad"
    result = find_largest_palindrome(test_string)
    print(f"Largest palindrome in '{test_string}': '{result}'")

# Additional function copied from elsewhere
def utility_function(x, y):
    """Utility function that appears to be copied"""
    return (x + y) * 2
'''

    create_zip_scenario("4_plagiarism", baseline_content, submission_content)

def create_empty_repo_scenario():
    """Scenario 5: Empty Repo - Baseline has no usable files"""
    print("Generating Empty Repo scenario...")

    # Baseline: Only documentation/files, no usable source code
    baseline_content = '''# Project Documentation
This project contains documentation and configuration files only.
No source code files for analysis are present in this repository.

## Files Included:
- README.md (this file)
- CONFIG.json
- LICENSE
'''

    baseline_readme = '''# Empty Repository
This repository intentionally contains no source code files.
It is used to test the system's handling of empty baselines.
'''

    baseline_config = '''{
    "project_name": "empty-test",
    "version": "1.0.0",
    "description": "Test repository with no source code"
}
'''

    baseline_license = '''MIT License

Copyright (c) 2023 Test Project

Permission is hereby granted...
'''

    # Submission: Actual Python source code for analysis
    submission_content = '''def binary_search(arr, target):
    """Perform binary search on sorted array"""
    left, right = 0, len(arr) - 1

    while left <= right:
        mid = (left + right) // 2
        if arr[mid] == target:
            return mid
        elif arr[mid] < target:
            left = mid + 1
        else:
            right = mid - 1

    return -1

def sort_and_search(data, target):
    """Sort data and then search for target"""
    sorted_data = sorted(data)
    return binary_search(sorted_data, target)

def main():
    # Test the search functionality
    numbers = [64, 34, 25, 12, 22, 11, 90, 5]
    target = 22

    index = sort_and_search(numbers, target)
    if index != -1:
        print(f"Found {target} at index {index}")
    else:
        print(f"{target} not found in list")

if __name__ == "__main__":
    main()
'''

    create_zip_scenario_with_readme("5_empty", baseline_content, baseline_readme, submission_content)

def create_cross_language_scenario():
    """Scenario 6: Cross-Language - Different programming languages"""
    print("Generating Cross-Language scenario...")

    # Baseline: Python implementation of a simple algorithm
    baseline_content = '''def fibonacci(n):
    """Calculate nth Fibonacci number using iterative approach"""
    if n <= 1:
        return n

    a, b = 0, 1
    for _ in range(2, n + 1):
        a, b = b, a + b
    return b

def fibonacci_series(count):
    """Generate Fibonacci series up to count elements"""
    series = []
    for i in range(count):
        series.append(fibonacci(i))
    return series

def main():
    # Generate first 10 Fibonacci numbers
    fib_series = fibonacci_series(10)
    print(f"Fibonacci series: {fib_series}")

    # Calculate specific values
    for i in [0, 1, 5, 10]:
        print(f"Fibonacci({i}) = {fibonacci(i)}")

if __name__ == "__main__":
    main()
'''

    # Submission: Same algorithm but implemented in JavaScript (different language)
    submission_content = '''/**
 * Calculate nth Fibonacci number using iterative approach
 * @param {number} n - Position in Fibonacci sequence
 * @returns {number} The nth Fibonacci number
 */
function fibonacci(n) {
    if (n <= 1) {
        return n;
    }

    let a = 0;
    let b = 1;
    for (let i = 2; i <= n; i++) {
        const temp = a + b;
        a = b;
        b = temp;
    }
    return b;
}

/**
 * Generate Fibonacci series up to count elements
 * @param {number} count - Number of elements to generate
 * @returns {number[]} Array containing Fibonacci series
 */
function fibonacciSeries(count) {
    const series = [];
    for (let i = 0; i < count; i++) {
        series.push(fibonacci(i));
    }
    return series;
}

// Main execution function
function main() {
    // Generate first 10 Fibonacci numbers
    const fibSeries = fibonacciSeries(10);
    console.log(`Fibonacci series: ${fibSeries}`);

    // Calculate specific values
    [0, 1, 5, 10].forEach(i => {
        console.log(`Fibonacci(${i}) = ${fibonacci(i)}`);
    });
}

// Run if executed directly
if (require.main === module) {
    main();
}
'''

    create_zip_scenario_internal("6_cross_language", baseline_content, submission_content, "python", "javascript")

def create_sophisticated_evasion_scenario():
    """Scenario 7: Sophisticated Evasion - AI trying to evade detection"""
    print("Generating Sophisticated Evasion scenario...")

    # Baseline: Simple, natural human-like code with variations
    baseline_content = '''def calculate_grade(score):
    """Calculate letter grade based on numerical score"""
    if score >= 90:
        return 'A'
    elif score >= 80:
        return 'B'
    elif score >= 70:
        return 'C'
    elif score >= 60:
        return 'D'
    else:
        return 'F'

def process_student_scores(scores):
    """Process a list of student scores and return grade distribution"""
    grades = {'A': 0, 'B': 0, 'C': 0, 'D': 0, 'F': 0}
    for score in scores:
        grade = calculate_grade(score)
        grades[grade] += 1
    return grades

def main():
    # Example usage with test data
    test_scores = [95, 87, 72, 68, 55, 91, 79, 82, 65, 58]
    distribution = process_student_scores(test_scores)

    print("Grade Distribution:")
    for grade, count in distribution.items():
        print(f"  {grade}: {count}")

if __name__ == "__main__":
    main()
'''

    # Submission: Sophisticated AI that tries to mimic human patterns but has subtle tells
    submission_content = '''def calculate_grade(score):
    """Calculate letter grade based on numerical score"""
    # AI-generated grading function with precise boundary detection
    if score >= 90:
        return 'A'
    elif score >= 80:
        return 'B'
    elif score >= 70:
        return 'C'
    elif score >= 60:
        return 'D'
    else:
        return 'F'

def process_student_scores(scores):
    """Process a list of student scores and return grade distribution"""
    # Initialize grade counters
    grades = {'A': 0, 'B': 0, 'C': 0, 'D': 0, 'F': 0}

    # Process each score with consistent logic
    for score in scores:
        grade = calculate_grade(score)
        grades[grade] = grades[grade] + 1  # Slightly unnatural increment pattern

    return grades

def main():
    # Example usage with carefully selected test data
    test_scores = [95, 87, 72, 68, 55, 91, 79, 82, 65, 58]
    distribution = process_student_scores(test_scores)

    # Output with AI-typical formatting
    print("Grade Distribution:")
    for grade in ['A', 'B', 'C', 'D', 'F']:  # Fixed order typical of AI
        count = distribution[grade]
        print(f"  {grade}: {count}")

# Entry point following AI conventions
if __name__ == "__main__":
    main()
'''

    create_zip_scenario("7_sophisticated_evasion", baseline_content, submission_content)

def create_template_subtraction_scenario():
    """Scenario 8: Template Subtraction - Testing template removal functionality"""
    print("Generating Template Subtraction scenario...")

    # Baseline: Contains template-like code that should be subtracted from analysis
    baseline_content = '''# ===== TEMPLATE SECTION START =====
# This section contains boilerplate/template code that should be ignored
# during code DNA analysis as it represents standard project scaffolding

PROJECT_NAME = "MyAwesomeProject"
VERSION = "1.0.0"
AUTHOR = "Developer Name"
CREATED_DATE = "2023-01-01"

def setup_logging():
    """Template function for setting up logging - should be subtracted"""
    import logging
    logging.basicConfig(level=logging.INFO)
    return logging.getLogger(__name__)

def load_config():
    """Template function for loading configuration - should be subtracted"""
    config = {
        "debug": False,
        "port": 8080,
        "host": "localhost"
    }
    return config

# ===== TEMPLATE SECTION END =====

# ===== ACTUAL STUDENT WORK BEGINS HERE =====

def calculate_factorial(n):
    """
    Calculate factorial of a number using recursion.
    This is the actual algorithmic work submitted by the student.
    """
    if n < 0:
        raise ValueError("Factorial is not defined for negative numbers")
    if n == 0 or n == 1:
        return 1
    return n * calculate_factorial(n - 1)

def is_prime(number):
    """
    Check if a number is prime.
    Another example of student's original work.
    """
    if number < 2:
        return False
    if number == 2:
        return True
    if number % 2 == 0:
        return False
    for i in range(3, int(number**0.5) + 1, 2):
        if number % i == 0:
            return False
    return True

def process_mathematical_operations(numbers):
    """
    Process a list of numbers through various mathematical operations.
    Demonstrates student's understanding of algorithms and functions.
    """
    results = {
        'factorials': [],
        'primes': [],
        'evens': [],
        'odds': []
    }

    for num in numbers:
        # Calculate factorial (for small numbers to avoid overflow)
        if 0 <= num <= 10:  # Limit to prevent excessive computation
            try:
                fact = calculate_factorial(num)
                results['factorials'].append(fact)
            except ValueError:
                results['factorials'].append(None)

        # Check if prime
        if is_prime(num):
            results['primes'].append(num)

        # Categorize even/odd
        if num % 2 == 0:
            results['evens'].append(num)
        else:
            results['odds'].append(num)

    return results

def main():
    """Main function demonstrating the student's work"""
    # Test data for mathematical operations
    test_numbers = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

    # Process the numbers
    results = process_mathematical_operations(test_numbers)

    # Display results
    print("Mathematical Operations Results:")
    print(f"  Factorials: {[f for f in results['factorials'] if f is not None]}")
    print(f"  Prime numbers: {results['primes']}")
    print(f"  Even numbers: {results['evens']}")
    print(f"  Odd numbers: {results['odds']}")

    # Additional validation
    print(f"  Count of numbers processed: {len(test_numbers)}")

# ===== END OF STUDENT WORK =====

if __name__ == "__main__":
    main()
'''

    # Template: Just the template code that should be subtracted during analysis
    template_content = '''# ===== TEMPLATE SECTION START =====
# This section contains boilerplate/template code that should be ignored
# during code DNA analysis as it represents standard project scaffolding

PROJECT_NAME = "MyAwesomeProject"
VERSION = "1.0.0"
AUTHOR = "Developer Name"
CREATED_DATE = "2023-01-01"

def setup_logging():
    """Template function for setting up logging - should be subtracted"""
    import logging
    logging.basicConfig(level=logging.INFO)
    return logging.getLogger(__name__)

def load_config():
    """Template function for loading configuration - should be subtracted"""
    config = {
        "debug": False,
        "port": 8080,
        "host": "localhost"
    }
    return config

# ===== TEMPLATE SECTION END =====
'''

    # Submission: Same as baseline (includes both template and student work)
    submission_content = baseline_content

    create_zip_scenario_with_template("8_template", baseline_content, submission_content, template_content)

def create_zip_scenario(scenario_name, baseline_content, submission_content):
    """Create a basic ZIP scenario with just baseline and submission"""
    create_zip_scenario_internal(scenario_name, baseline_content, submission_content, None, None)

def create_zip_scenario_with_readme(scenario_name, baseline_content, baseline_readme, submission_content):
    """Create a ZIP scenario with baseline having extra README file"""
    scenario_dir = Path(f"test_data/{scenario_name}")
    scenario_dir.mkdir(parents=True, exist_ok=True)

    # Create baseline ZIP with main.py and README.md
    baseline_zip = scenario_dir / "baseline.zip"
    with zipfile.ZipFile(baseline_zip, 'w', zipfile.ZIP_DEFLATED) as zf:
        zf.writestr("main.py", baseline_content)
        zf.writestr("README.md", baseline_readme)

    # Create submission ZIP with just main.py
    submission_zip = scenario_dir / "submission.zip"
    with zipfile.ZipFile(submission_zip, 'w', zipfile.ZIP_DEFLATED) as zf:
        zf.writestr("main.py", submission_content)

    print(f"  Created {baseline_zip} and {submission_zip}")

def create_zip_scenario_with_template(scenario_name, baseline_content, submission_content, template_content):
    """Create a ZIP scenario with baseline, submission, and template"""
    scenario_dir = Path(f"test_data/{scenario_name}")
    scenario_dir.mkdir(parents=True, exist_ok=True)

    # Create baseline ZIP
    baseline_zip = scenario_dir / "baseline.zip"
    with zipfile.ZipFile(baseline_zip, 'w', zipfile.ZIP_DEFLATED) as zf:
        zf.writestr("main.py", baseline_content)

    # Create submission ZIP
    submission_zip = scenario_dir / "submission.zip"
    with zipfile.ZipFile(submission_zip, 'w', zipfile.ZIP_DEFLATED) as zf:
        zf.writestr("main.py", submission_content)

    # Create template ZIP
    template_zip = scenario_dir / "template.zip"
    with zipfile.ZipFile(template_zip, 'w', zipfile.ZIP_DEFLATED) as zf:
        zf.writestr("template.py", template_content)

    print(f"  Created {baseline_zip}, {submission_zip}, and {template_zip}")

def create_zip_scenario_internal(scenario_name, baseline_content, submission_content, baseline_lang=None, submission_lang=None):
    """Internal function to create ZIP files for a scenario"""
    scenario_dir = Path(f"test_data/{scenario_name}")
    scenario_dir.mkdir(parents=True, exist_ok=True)

    # Determine filenames based on language
    baseline_filename = "main.py" if baseline_lang != "javascript" else "main.js"
    submission_filename = "main.py" if submission_lang != "javascript" else "main.js"

    # Create baseline ZIP
    baseline_zip = scenario_dir / "baseline.zip"
    with zipfile.ZipFile(baseline_zip, 'w', zipfile.ZIP_DEFLATED) as zf:
        zf.writestr(baseline_filename, baseline_content)

    # Create submission ZIP
    submission_zip = scenario_dir / "submission.zip"
    with zipfile.ZipFile(submission_zip, 'w', zipfile.ZIP_DEFLATED) as zf:
        zf.writestr(submission_filename, submission_content)

    print(f"  Created {baseline_zip} and {submission_zip}")

def main():
    """Generate all test scenarios"""
    print("=== Generating Test Data for Phase 3 Extreme Automated Testing ===")

    # Clean test_data directory
    test_data_dir = Path("test_data")
    if test_data_dir.exists():
        shutil.rmtree(test_data_dir)
    test_data_dir.mkdir()

    # Generate all scenarios
    create_clean_student_scenario()
    create_sudden_ai_scenario()
    create_consistent_ai_scenario()
    create_plagiarism_scenario()
    create_empty_repo_scenario()
    create_cross_language_scenario()
    create_sophisticated_evasion_scenario()
    create_template_subtraction_scenario()

    print("\n=== Test Data Generation Complete ===")
    print("Generated scenarios:")
    print("1. Clean Student - Minor natural evolution (structural deviation < 20)")
    print("2. Sudden AI - Clear introduction of AI patterns (ai_author_profile = 'Sudden AI Introduction')")
    print("3. Consistent AI - Baseline already has AI patterns (ai_author_profile = 'Consistent AI Author')")
    print("4. Plagiarism - High concern due to copied structure (overall_investigation_concern = 'High')")
    print("5. Empty Repo - Baseline has no usable files (baseline_reliability = 'Low')")
    print("6. Cross-Language - Different programming languages (architecture_deviation > 60)")
    print("7. Sophisticated Evasion - AI trying to evade detection (overall deviation score > 25)")
    print("8. Template Subtraction - Testing template removal functionality")

if __name__ == "__main__":
    main()